import validator from 'validator';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import userModel from '../models/userModel.js';

const createToken = (id) =>{
    // return token is created by jwt package 
    //in here need to give id and secrete key that we create mannually
    return jwt.sign({id},process.env.JWT_SECRET)
}


//add the login we can allow user to create an account or login on the website
//so we need to create two arrow function loginuser an dregisteruser

//Route for user login
const loginUser = async (req,res) => {
    try {
        //first need to get email and password from request body
        const {email,password} = req.body;

        //if user is not avasilable from this email we need to give responce
        const user = await userModel.findOne({email});
        if(!user){
            return res.json({success:false, message:"User does not exists"})
        }

        //if the user email is correct then need to check password
        const isMatch = await bcrypt.compare(password, user.password) //password-> keyboard input password , user.password-> db saved password
        if(isMatch){
            // if the isMatch true it will generate one token and send that token to the user
            const token = createToken(user._id)
            res.json({super:true, token})
        }
        else{
            res.json({success:false, message:"Invalid credentials"})
        }
    } catch (error) {
        console.log(error);
        res.json({success:false, message: error.message})
    }
} 

//Router for use registration
const registerUser = async (req,res) => {
    try {
        const {name, email, password} = req.body;

        //checking user already exixt or not - check by email
        const exists = await userModel.findOne({email});
        if(exists) {
            return res.json({success:false, message:"User already exixts"})
        }

        //validate emai format and strong password
        if(!validator.isEmail(email)){
            return res.json({success:false, message:"Please enter valid email"})
        }
        if(password.length < 8){
            return res.json({success:false, message:"Please enter strong password"})
        }

        //hashing user password
        const salt = await bcrypt.genSalt(10)
        const hashedPassword = await bcrypt.hash(password, salt)

        //after all are checking need to create user
        const newUser = new userModel({
            name,
            email,
            password: hashedPassword
        })

        //save this user in our database
        const  user = await newUser.save()

        //after storing the use in db need to provide token using that user can login in application
        //token is create using the id property of user
        // when the user will be create then _id property is generated by default and isong thi id we generate one token
        // to generate the token need to make arrow funtion
        const token = createToken(user._id)

        //after create token we have to set this token as a response
        res.json({success:true, token})
        
    } catch (error) {
        console.log(error);
        res.json({success:false, message: error.message})
    }
}

// Route for admin login
const adminLogin = async (req,res)=> {
    try {
        const {email,password} = req.body

        if(email === process.env.ADMIN_EMAIL && password === process.env.ADMIN_PASSWORD){
            const token = jwt.sign(email+password,process.env.JWT_SECRET);
            res.json({success:true, token})
        }else{
            res.json({success:false, message:"Invalid Credentials"})
        }
    } catch (error) {
        console.log(error)
        res.json({success:false, message:error.message})
    }
}

export {loginUser, registerUser, adminLogin} 